# Generated by Django 5.2.6 on 2025-09-21 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baby',
            unique_together={('owner', 'name')},
        ),
        migrations.RemoveField(
            model_name='baby',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='baby',
            name='sex',
        ),
    ]
