# Generated by Django 5.2.6 on 2025-10-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fooditem_foodentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='user',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='baby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='core.baby'),
            preserve_default=False,
        ),
    ]
