# Generated by Django 5.2.6 on 2025-09-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_baby_unique_together_remove_baby_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
