# Generated by Django 5.2.6 on 2025-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_foodcategory_userfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='portion_unit',
            field=models.CharField(choices=[('oz', 'oz'), ('fl oz', 'fl oz'), ('g', 'g'), ('ml', 'ml')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='portion_size',
            field=models.FloatField(),
        ),
    ]
