# Generated by Django 5.2.7 on 2025-10-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foodentry_portion_unit_alter_foodentry_portion_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfood',
            name='calories',
            field=models.FloatField(default=0, help_text='per 100g'),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='carbs',
            field=models.FloatField(default=0, help_text='per 100g'),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='fats',
            field=models.FloatField(default=0, help_text='per 100g'),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='protein',
            field=models.FloatField(default=0, help_text='per 100g'),
        ),
    ]
