# Generated by Django 5.2.7 on 2025-11-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userfood_calories_alter_userfood_carbs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('calories_100g', models.FloatField(default=0)),
                ('protein_100g', models.FloatField(default=0)),
                ('carbs_100g', models.FloatField(default=0)),
                ('fats_100g', models.FloatField(default=0)),
                ('fdc_id', models.BigIntegerField(blank=True, null=True)),
                ('data_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_foods', to='core.foodcategory')),
            ],
            options={
                'ordering': ['category__pyramid_level', 'name'],
            },
        ),
    ]
