# Generated by Django 5.2.6 on 2025-11-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_catalogfood"),
    ]

    operations = [
        migrations.AddField(
            model_name="baby",
            name="stock_avatar",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
