# Generated by Django 5.2.7 on 2025-11-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_catalogfood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogfood',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['name']},
        ),
    ]
