# Generated by Django 5.2.7 on 2025-11-17 22:11

from django.db import migrations


def seed_food_categories(apps, schema_editor):
    FoodCategory = apps.get_model("core", "FoodCategory")

    categories = [
        ("Vegetables", 1),
        ("Fruits", 1),
        ("Grains & Starches", 2),
        ("Proteins", 3),
        ("Dairy", 3),
        ("Fats & Oils", 4),
        ("Sweets & Processed Foods", 5),
    ]

    for name, level in categories:
        FoodCategory.objects.get_or_create(
            name=name,
            defaults={"pyramid_level": level},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_catalogfood_options_alter_foodcategory_options'),
    ]

    operations = [
        migrations.RunPython(seed_food_categories),
    ]
