# Generated by Django 5.2.7 on 2025-11-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_baby_stock_avatar'),
        ('core', '0009_seed_food_categories'),
    ]

    operations = [
    ]
