# Generated by Django 5.2.6 on 2025-11-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20251117_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='reaction',
            field=models.CharField(blank=True, choices=[('love', 'Loved it'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('gross', 'Gross')], max_length=10),
        ),
    ]
