# Generated by Django 5.2.6 on 2025-11-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_foodentry_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodentry",
            name="portion_unit",
            field=models.CharField(
                choices=[
                    ("g", "g"),
                    ("oz", "oz"),
                    ("ml", "ml"),
                    ("cup", "cup"),
                    ("half", "half"),
                    ("fl oz", "fl oz"),
                    ("piece", "piece"),
                    ("whole", "whole"),
                    ("serving", "serving"),
                    ("slice", "slice"),
                    ("tbsp", "tbsp"),
                    ("tsp", "tsp"),
                ],
                default="g",
                max_length=10,
            ),
        ),
    ]
