# Generated by Django 5.2.6 on 2025-11-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_foodentry_portion_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='catalog_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to='core.catalogfood'),
        ),
    ]
